const furniture = [
  {
    id: 61,
    brand: "Urban Ladder",
    details: "3-Seater Sofa",
    description: "Modern fabric sofa with plush cushions and wooden legs.",
    price: 14999,
    orgprice: 29999,
    off: "50",
    color: "grey",
    gender: "unisex",
    image: "/sofa.png",
    otherImages: ["/sofa-1.png", "/sofa-2.png"],
    reviews: [{ rating: 5, comment: "Super comfy!" }]
  },
  {
    id: 62,
    brand: "IKEA",
    details: "Floor Lamp",
    description: "Minimalist lamp with adjustable brightness.",
    price: 1999,
    orgprice: 3999,
    off: "50",
    color: "white",
    gender: "unisex",
    image: "/lamp.png",
    otherImages: ["/lamp-1.png", "/lamp-2.png"],
    reviews: [{ rating: 4, comment: "Elegant design." }]
  },
  {
    id: 63,
    brand: "Pepperfry",
    details: "Coffee Table",
    description: "Wooden coffee table with storage shelf.",
    price: 3499,
    orgprice: 6999,
    off: "50",
    color: "walnut",
    gender: "unisex",
    image: "/coffee-table.png",
    otherImages: ["/coffee-table-1.png", "/coffee-table-2.png"],
    reviews: [{ rating: 5, comment: "Looks great in living room." }]
  },
  {
    id: 64,
    brand: "Nilkamal",
    details: "Plastic Chair Set",
    description: "Set of 2 durable plastic chairs for outdoor use.",
    price: 1299,
    orgprice: 2599,
    off: "50",
    color: "brown",
    gender: "unisex",
    image: "/plastic-chairs.png",
    otherImages: ["/plastic-chairs-1.png", "/plastic-chairs-2.png"],
    reviews: [{ rating: 4, comment: "Lightweight and sturdy." }]
  },
  {
    id: 65,
    brand: "Home Centre",
    details: "Bookshelf",
    description: "5-tier bookshelf with modern design.",
    price: 2499,
    orgprice: 4999,
    off: "50",
    color: "oak",
    gender: "unisex",
    image: "/bookshelf.png",
    otherImages: ["/bookshelf-1.png", "/bookshelf-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for organizing." }]
  },
  {
    id: 66,
    brand: "Durian",
    details: "Office Chair",
    description: "Ergonomic chair with lumbar support.",
    price: 3999,
    orgprice: 7999,
    off: "50",
    color: "black",
    gender: "unisex",
    image: "/office-chair.png",
    otherImages: ["/office-chair-1.png", "/office-chair-2.png"],
    reviews: [{ rating: 5, comment: "Great for long hours." }]
  },
  {
    id: 67,
    brand: "Wakefit",
    details: "Queen Mattress",
    description: "Memory foam mattress with orthopedic support.",
    price: 8999,
    orgprice: 17999,
    off: "50",
    color: "white",
    gender: "unisex",
    image: "/mattress.png",
    otherImages: ["/mattress-1.png", "/mattress-2.png"],
    reviews: [{ rating: 5, comment: "Best sleep ever!" }]
  },
  {
    id: 68,
    brand: "Godrej Interio",
    details: "Wardrobe",
    description: "3-door wardrobe with mirror and drawers.",
    price: 11999,
    orgprice: 23999,
    off: "50",
    color: "mahogany",
    gender: "unisex",
    image: "/wardrobe.png",
    otherImages: ["/wardrobe-1.png", "/wardrobe-2.png"],
    reviews: [{ rating: 4, comment: "Spacious and elegant." }]
  },
  {
    id: 69,
    brand: "Flipkart Perfect Homes",
    details: "TV Unit",
    description: "Compact TV unit with cable management.",
    price: 2999,
    orgprice: 5999,
    off: "50",
    color: "black",
    gender: "unisex",
    image: "/tv-unit.png",
    otherImages: ["/tv-unit-1.png", "/tv-unit-2.png"],
    reviews: [{ rating: 5, comment: "Neat and functional." }]
  },
  {
    id: 70,
    brand: "Spacewood",
    details: "Study Table",
    description: "Engineered wood table with drawers and shelf.",
    price: 3499,
    orgprice: 6999,
    off: "50",
    color: "teak",
    gender: "unisex",
    image: "/study-table.png",
    otherImages: ["/study-table-1.png", "/study-table-2.png"],
    reviews: [{ rating: 4, comment: "Perfect for students." }]
  }
];

export default furniture;