const kids = [
  {
    id: 51,
    brand: "Hopscotch",
    details: "Kids Party Dress",
    description: "Cute floral dress with frills and bow tie.",
    price: 599,
    orgprice: 1199,
    off: "50",
    color: "pink",
    gender: "girls",
    image: "/kids-dress.png",
    otherImages: ["/kids-dress-1.png", "/kids-dress-2.png"],
    reviews: [{ rating: 5, comment: "Adorable!" }]
  },
  {
    id: 52,
    brand: "Babyhug",
    details: "Boys T-Shirt",
    description: "Cotton tee with cartoon print.",
    price: 299,
    orgprice: 599,
    off: "50",
    color: "yellow",
    gender: "boys",
    image: "/kids-tshirt.png",
    otherImages: ["/kids-tshirt-1.png", "/kids-tshirt-2.png"],
    reviews: [{ rating: 4, comment: "Bright and fun." }]
  },
  {
    id: 53,
    brand: "FirstCry",
    details: "Kids Shoes",
    description: "Velcro shoes with soft sole.",
    price: 499,
    orgprice: 999,
    off: "50",
    color: "blue",
    gender: "kids",
    image: "/kids-shoes.png",
    otherImages: ["/kids-shoes-1.png", "/kids-shoes-2.png"],
    reviews: [{ rating: 5, comment: "Easy to wear." }]
  },
  {
    id: 54,
    brand: "Mothercare",
    details: "Baby Romper",
    description: "Cotton romper with snap buttons.",
    price: 399,
    orgprice: 799,
    off: "50",
    color: "white",
    gender: "infant",
    image: "/baby-romper.png",
    otherImages: ["/baby-romper-1.png", "/baby-romper-2.png"],
    reviews: [{ rating: 5, comment: "Soft and gentle." }]
  },
  {
    id: 55,
    brand: "Chicco",
    details: "Kids Jacket",
    description: "Warm jacket with hood and zipper.",
    price: 899,
    orgprice: 1799,
    off: "50",
    color: "red",
    gender: "kids",
    image: "/kids-jacket.png",
    otherImages: ["/kids-jacket-1.png", "/kids-jacket-2.png"],
    reviews: [{ rating: 4, comment: "Cozy and cute." }]
  },
  {
    id: 56,
    brand: "Mini Klub",
    details: "Girls Leggings",
    description: "Stretchable leggings with fun prints.",
    price: 349,
    orgprice: 699,
    off: "50",
    color: "purple",
    gender: "girls",
    image: "/kids-leggings.png",
    otherImages: ["/kids-leggings-1.png", "/kids-leggings-2.png"],
    reviews: [{ rating: 5, comment: "Great fit!" }]
  },
  {
    id: 57,
    brand: "ToffyHouse",
    details: "Boys Shorts",
    description: "Cotton shorts with elastic waist.",
    price: 299,
    orgprice: 599,
    off: "50",
    color: "green",
    gender: "boys",
    image: "/kids-shorts.png",
    otherImages: ["/kids-shorts-1.png", "/kids-shorts-2.png"],
    reviews: [{ rating: 4, comment: "Good for playtime." }]
  },
    {
    id: 58,
    brand: "LuvLap",
    details: "Baby Stroller",
    description: "Foldable stroller with safety harness and canopy.",
    price: 2999,
    orgprice: 5999,
    off: "50",
    color: "grey",
    gender: "infant",
    image: "/baby-stroller.png",
    otherImages: ["/baby-stroller-1.png", "/baby-stroller-2.png"],
    reviews: [{ rating: 5, comment: "Very smooth ride." }]
  },
  {
    id: 59,
    brand: "Hamleys",
    details: "Kids Puzzle Set",
    description: "Colorful puzzle set for cognitive development.",
    price: 499,
    orgprice: 999,
    off: "50",
    color: "multi",
    gender: "kids",
    image: "/kids-puzzle.png",
    otherImages: ["/kids-puzzle-1.png", "/kids-puzzle-2.png"],
    reviews: [{ rating: 4, comment: "Keeps them engaged." }]
  },
  {
    id: 60,
    brand: "Hot Wheels",
    details: "Toy Car Pack",
    description: "Set of 5 die-cast cars with cool designs.",
    price: 699,
    orgprice: 1399,
    off: "50",
    color: "multi",
    gender: "boys",
    image: "/toy-cars.png",
    otherImages: ["/toy-cars-1.png", "/toy-cars-2.png"],
    reviews: [{ rating: 5, comment: "Super fun!" }]
  }
];

export default kids;