const accessories = [
  {
    id: 41,
    brand: "Fossil",
    details: "Leather Belt",
    description: "Premium brown leather belt with metal buckle.",
    price: 799,
    orgprice: 1599,
    off: "50",
    color: "brown",
    gender: "men",
    image: "/belt.png",
    otherImages: ["/belt-1.png", "/belt-2.png"],
    reviews: [{ rating: 5, comment: "High quality leather." }]
  },
  {
    id: 42,
    brand: "Tommy Hilfiger",
    details: "Canvas Belt",
    description: "Casual canvas belt with logo buckle.",
    price: 899,
    orgprice: 1799,
    off: "50",
    color: "navy",
    gender: "men",
    image: "/canvas-belt.png",
    otherImages: ["/canvas-belt-1.png", "/canvas-belt-2.png"],
    reviews: [{ rating: 4, comment: "Stylish and sturdy." }]
  },
  {
    id: 43,
    brand: "Allen Solly",
    details: "Formal Tie",
    description: "Silk tie with subtle pattern.",
    price: 499,
    orgprice: 999,
    off: "50",
    color: "grey",
    gender: "men",
    image: "/tie.png",
    otherImages: ["/tie-1.png", "/tie-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for meetings." }]
  },
  {
    id: 44,
    brand: "Ray-Ban",
    details: "Sunglasses",
    description: "UV-protected aviator sunglasses.",
    price: 1999,
    orgprice: 3999,
    off: "50",
    color: "black",
    gender: "unisex",
    image: "/sunglasses.png",
    otherImages: ["/sunglasses-1.png", "/sunglasses-2.png"],
    reviews: [{ rating: 5, comment: "Looks premium." }]
  },
  {
    id: 45,
    brand: "Titan",
    details: "Analog Watch",
    description: "Classic watch with leather strap.",
    price: 2499,
    orgprice: 4999,
    off: "50",
    color: "brown",
    gender: "men",
    image: "/watch.png",
    otherImages: ["/watch-1.png", "/watch-2.png"],
    reviews: [{ rating: 5, comment: "Elegant design." }]
  },
  {
    id: 46,
    brand: "Daniel Wellington",
    details: "Women Watch",
    description: "Minimalist watch with rose gold finish.",
    price: 2999,
    orgprice: 5999,
    off: "50",
    color: "rose gold",
    gender: "women",
    image: "/dw-watch.png",
    otherImages: ["/dw-watch-1.png", "/dw-watch-2.png"],
    reviews: [{ rating: 4, comment: "Very classy." }]
  },
  {
    id: 47,
    brand: "WildHorn",
    details: "Wallet",
    description: "Genuine leather wallet with multiple compartments.",
    price: 699,
    orgprice: 1399,
    off: "50",
    color: "black",
    gender: "men",
    image: "/wallet.png",
    otherImages: ["/wallet-1.png", "/wallet-2.png"],
    reviews: [{ rating: 5, comment: "Spacious and durable." }]
  },
  {
    id: 48,
    brand: "Lavie",
    details: "Women Handbag",
    description: "Textured handbag with zip closure.",
    price: 1499,
    orgprice: 2999,
    off: "50",
    color: "red",
    gender: "women",
    image: "/handbag.png",
    otherImages: ["/handbag-1.png", "/handbag-2.png"],
    reviews: [{ rating: 4, comment: "Stylish and roomy." }]
  },
  {
    id: 49,
    brand: "Caprese",
    details: "Tote Bag",
    description: "Elegant tote with inner organizer.",
    price: 1799,
    orgprice: 3599,
    off: "50",
    color: "blue",
    gender: "women",
    image: "/tote.png",
    otherImages: ["/tote-1.png", "/tote-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for work." }]
  },
  {
    id: 50,
    brand: "American Tourister",
    details: "Backpack",
    description: "Durable backpack with laptop compartment.",
    price: 1299,
    orgprice: 2599,
    off: "50",
    color: "grey",
    gender: "unisex",
    image: "/backpack.png",
    otherImages: ["/backpack-1.png", "/backpack-2.png"],
    reviews: [{ rating: 4, comment: "Great for travel." }]
  }
];

export default accessories;