const beauty = [
  {
    id: 21,
    brand: "Maybelline",
    details: "Matte Lipstick",
    description: "Long-lasting matte finish with vibrant color.",
    price: 299,
    orgprice: 599,
    off: "50",
    color: "red",
    gender: "unisex",
    image: "/lipstick.png",
    otherImages: ["/lipstick-1.png", "/lipstick-2.png"],
    reviews: [{ rating: 5, comment: "Stays all day!" }]
  },
  {
    id: 22,
    brand: "Lakme",
    details: "Kajal Pencil",
    description: "Smudge-proof kajal for bold eyes.",
    price: 149,
    orgprice: 299,
    off: "50",
    color: "black",
    gender: "unisex",
    image: "/kajal.png",
    otherImages: ["/kajal-1.png", "/kajal-2.png"],
    reviews: [{ rating: 4, comment: "Intense color." }]
  },
  {
    id: 23,
    brand: "L'Oreal",
    details: "Hydrating Serum",
    description: "Vitamin C serum for glowing skin.",
    price: 499,
    orgprice: 999,
    off: "50",
    color: "transparent",
    gender: "unisex",
    image: "/serum.png",
    otherImages: ["/serum-1.png", "/serum-2.png"],
    reviews: [{ rating: 5, comment: "Skin feels fresh!" }]
  },
  {
    id: 24,
    brand: "Nykaa",
    details: "Nail Paint Set",
    description: "Glossy nail paints in vibrant shades.",
    price: 399,
    orgprice: 799,
    off: "50",
    color: "multi",
    gender: "women",
    image: "/nailpaint.png",
    otherImages: ["/nailpaint-1.png", "/nailpaint-2.png"],
    reviews: [{ rating: 4, comment: "Great colors!" }]
  },
  {
    id: 25,
    brand: "The Body Shop",
    details: "Face Wash",
    description: "Tea tree face wash for oily skin.",
    price: 349,
    orgprice: 699,
    off: "50",
    color: "green",
    gender: "unisex",
    image: "/facewash.png",
    otherImages: ["/facewash-1.png", "/facewash-2.png"],
    reviews: [{ rating: 5, comment: "Refreshing!" }]
  },
  {
    id: 26,
    brand: "Plum",
    details: "Moisturizer",
    description: "Lightweight moisturizer for daily use.",
    price: 299,
    orgprice: 599,
    off: "50",
    color: "white",
    gender: "unisex",
    image: "/moisturizer.png",
    otherImages: ["/moisturizer-1.png", "/moisturizer-2.png"],
    reviews: [{ rating: 4, comment: "Non-greasy." }]
  },
  {
    id: 27,
    brand: "Mamaearth",
    details: "Hair Oil",
    description: "Onion hair oil for hair growth.",
    price: 399,
    orgprice: 799,
    off: "50",
    color: "amber",
    gender: "unisex",
    image: "/hairoil.png",
    otherImages: ["/hairoil-1.png", "/hairoil-2.png"],
    reviews: [{ rating: 5, comment: "Works well!" }]
  },
  {
    id: 28,
    brand: "Biotique",
    details: "Sunscreen Lotion",
    description: "SPF 50 lotion for sun protection.",
    price: 249,
    orgprice: 499,
    off: "50",
    color: "yellow",
    gender: "unisex",
    image: "/sunscreen.png",
    otherImages: ["/sunscreen-1.png", "/sunscreen-2.png"],
    reviews: [{ rating: 4, comment: "No white cast." }]
  },
  {
    id: 29,
    brand: "Colorbar",
    details: "Foundation",
    description: "Liquid foundation with matte finish.",
    price: 699,
    orgprice: 1399,
    off: "50",
    color: "beige",
    gender: "women",
    image: "/foundation.png",
    otherImages: ["/foundation-1.png", "/foundation-2.png"],
    reviews: [{ rating: 5, comment: "Blends well!" }]
  },
  {
    id: 30,
    brand: "Revlon",
    details: "Compact Powder",
    description: "Oil-control compact for daily wear.",
    price: 349,
    orgprice: 699,
    off: "50",
    color: "ivory",
    gender: "women",
    image: "/compact.png",
    otherImages: ["/compact-1.png", "/compact-2.png"],
    reviews: [{ rating: 4, comment: "Good coverage." }]
  },

];

export default beauty;