const footwear = [
  {
    id: 31,
    brand: "Nike",
    details: "Men Running Shoes",
    description: "Lightweight shoes with breathable mesh and cushioned sole.",
    price: 2499,
    orgprice: 4999,
    off: "50",
    color: "black",
    gender: "men",
    image: "/nike-shoes.png",
    otherImages: ["/nike-shoes-1.png", "/nike-shoes-2.png"],
    reviews: [{ rating: 5, comment: "Super comfy!" }]
  },
  {
    id: 32,
    brand: "Adidas",
    details: "Women Sneakers",
    description: "Stylish sneakers with cloudfoam comfort.",
    price: 2299,
    orgprice: 4599,
    off: "50",
    color: "white",
    gender: "women",
    image: "/adidas-sneakers.png",
    otherImages: ["/adidas-sneakers-1.png", "/adidas-sneakers-2.png"],
    reviews: [{ rating: 4, comment: "Great for walking." }]
  },
  {
    id: 33,
    brand: "Puma",
    details: "Unisex Slides",
    description: "Water-resistant slides with soft footbed.",
    price: 799,
    orgprice: 1599,
    off: "50",
    color: "blue",
    gender: "unisex",
    image: "/puma-slides.png",
    otherImages: ["/puma-slides-1.png", "/puma-slides-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for poolside." }]
  },
  {
    id: 34,
    brand: "Bata",
    details: "Men Formal Shoes",
    description: "Classic lace-up shoes for office wear.",
    price: 1499,
    orgprice: 2999,
    off: "50",
    color: "brown",
    gender: "men",
    image: "/bata-formal.png",
    otherImages: ["/bata-formal-1.png", "/bata-formal-2.png"],
    reviews: [{ rating: 4, comment: "Elegant and durable." }]
  },
  {
    id: 35,
    brand: "Crocs",
    details: "Kids Clogs",
    description: "Lightweight clogs with ventilation ports.",
    price: 999,
    orgprice: 1999,
    off: "50",
    color: "green",
    gender: "kids",
    image: "/crocs-kids.png",
    otherImages: ["/crocs-kids-1.png", "/crocs-kids-2.png"],
    reviews: [{ rating: 5, comment: "Kids love them!" }]
  },
  {
    id: 36,
    brand: "Woodland",
    details: "Men Hiking Boots",
    description: "Rugged boots with high ankle support.",
    price: 2999,
    orgprice: 5999,
    off: "50",
    color: "tan",
    gender: "men",
    image: "/woodland-boots.png",
    otherImages: ["/woodland-boots-1.png", "/woodland-boots-2.png"],
    reviews: [{ rating: 5, comment: "Great for trekking." }]
  },
  {
    id: 37,
    brand: "Sketchers",
    details: "Women Walking Shoes",
    description: "Memory foam insoles for all-day comfort.",
    price: 1999,
    orgprice: 3999,
    off: "50",
    color: "pink",
    gender: "women",
    image: "/sketchers-women.png",
    otherImages: ["/sketchers-women-1.png", "/sketchers-women-2.png"],
    reviews: [{ rating: 4, comment: "Very soft!" }]
  },
  {
    id: 38,
    brand: "Campus",
    details: "Men Sports Shoes",
    description: "Affordable sports shoes with mesh upper.",
    price: 1299,
    orgprice: 2599,
    off: "50",
    color: "grey",
    gender: "men",
    image: "/campus-sports.png",
    otherImages: ["/campus-sports-1.png", "/campus-sports-2.png"],
    reviews: [{ rating: 4, comment: "Value for money." }]
  },
  {
    id: 39,
    brand: "Liberty",
    details: "Women Heels",
    description: "Block heels with ankle strap.",
    price: 999,
    orgprice: 1999,
    off: "50",
    color: "red",
    gender: "women",
    image: "/liberty-heels.png",
    otherImages: ["/liberty-heels-1.png", "/liberty-heels-2.png"],
    reviews: [{ rating: 5, comment: "Elegant look." }]
  },
  {
    id: 40,
    brand: "Red Tape",
    details: "Men Loafers",
    description: "Slip-on loafers with cushioned sole.",
    price: 1399,
    orgprice: 2799,
    off: "50",
    color: "navy",
    gender: "men",
    image: "/redtape-loafers.png",
    otherImages: ["/redtape-loafers-1.png", "/redtape-loafers-2.png"],
    reviews: [{ rating: 4, comment: "Comfortable for daily wear." }]
  }
];

export default footwear;