const data = [
  {
    id: 1,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 2,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 3,
    image: "cardimg.png",
    brand: "SoleStore",
    details: "Men Casual Shirt",
    price: 1499,
    orgprice: 1999,
    off: "80",
    color: "black",
    gender: "women",
  },
  {
    id: 4,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "80",
    color: "pink",
    gender: "women",
  },
];

export default data;