const data = [
  {
    id: 1,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 2,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 3,
    image: "cardimg.png",
    brand: "SoleStore",
    details: "Men Casual Shirt",
    price: 1499,
    orgprice: 1999,
    off: "80",
    color: "black",
    gender: "women",
  },
  {
    id: 4,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "80",
    color: "pink",
    gender: "women",
  },
  {
    id: 5,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 2499,
    orgprice: 2999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 6,
    image: "cardimg.png",
    brand: "POLO",
    details: "Men Casual Shirt",
    price: 1499,
    orgprice: 2999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 7,
    image: "cardimg.png",
    brand: "SoleStore",
    details: "Men Casual Shirt",
    price: 1999,
    orgprice: 2999,
    off: "80",
    color: "black",
    gender: "women",
  },
  {
    id: 8,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 999,
    orgprice: 1999,
    off: "80",
    color: "pink",
    gender: "women",
  },
  {
    id: 9,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 10,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 11,
    image: "cardimg.png",
    brand: "SoleStore",
    details: "Men Casual Shirt",
    price: 1499,
    orgprice: 1999,
    off: "80",
    color: "black",
    gender: "women",
  },
  {
    id: 12,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 499,
    orgprice: 999,
    off: "80",
    color: "pink",
    gender: "women",
  },
  {
    id: 13,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 2499,
    orgprice: 2999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 14,
    image: "cardimg.png",
    brand: "POLO",
    details: "Men Casual Shirt",
    price: 1499,
    orgprice: 2999,
    off: "60",
    color: "white",
    gender: "men",
  },
  {
    id: 15,
    image: "cardimg.png",
    brand: "SoleStore",
    details: "Men Casual Shirt",
    price: 1999,
    orgprice: 2999,
    off: "80",
    color: "black",
    gender: "women",
  },
  {
    id: 16,
    image: "cardimg.png",
    brand: "Highlander",
    details: "Men Casual Shirt",
    price: 999,
    orgprice: 1999,
    off: "80",
    color: "pink",
    gender: "women",
  },
];

export default data;