const womenClothing = [
  {
    id: 11,
    brand: "Biba",
    details: "Ethnic Kurti",
    description: "Elegant printed kurti with mandarin collar.",
    price: 899,
    orgprice: 1799,
    off: "50",
    color: "maroon",
    gender: "women",
    image: "/women-kurti.png",
    otherImages: ["/women-kurti-1.png", "/women-kurti-2.png"],
    reviews: [{ rating: 5, comment: "Beautiful design!" }]
  },
  {
    id: 12,
    brand: "Zara",
    details: "Women Crop Top",
    description: "Trendy crop top with ribbed texture.",
    price: 599,
    orgprice: 1199,
    off: "50",
    color: "black",
    gender: "women",
    image: "/women-crop.png",
    otherImages: ["/women-crop-1.png", "/women-crop-2.png"],
    reviews: [{ rating: 4, comment: "Stylish and comfy." }]
  },
  {
    id: 13,
    brand: "H&M",
    details: "Women Maxi Dress",
    description: "Flowy floral maxi dress with side slit.",
    price: 1299,
    orgprice: 2599,
    off: "50",
    color: "blue",
    gender: "women",
    image: "/women-maxi.png",
    otherImages: ["/women-maxi-1.png", "/women-maxi-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for summer!" }]
  },
  {
    id: 14,
    brand: "Forever 21",
    details: "Women Denim Skirt",
    description: "High-waisted denim skirt with frayed hem.",
    price: 799,
    orgprice: 1599,
    off: "50",
    color: "light blue",
    gender: "women",
    image: "/women-skirt.png",
    otherImages: ["/women-skirt-1.png", "/women-skirt-2.png"],
    reviews: [{ rating: 4, comment: "Cute and casual." }]
  },
  {
    id: 15,
    brand: "AND",
    details: "Women Blazer",
    description: "Tailored blazer with notch lapel.",
    price: 1499,
    orgprice: 2999,
    off: "50",
    color: "beige",
    gender: "women",
    image: "/women-blazer.png",
    otherImages: ["/women-blazer-1.png", "/women-blazer-2.png"],
    reviews: [{ rating: 5, comment: "Looks professional." }]
  },
  {
    id: 16,
    brand: "FabIndia",
    details: "Women Cotton Saree",
    description: "Handwoven cotton saree with ethnic motifs.",
    price: 1799,
    orgprice: 3599,
    off: "50",
    color: "green",
    gender: "women",
    image: "/women-saree.png",
    otherImages: ["/women-saree-1.png", "/women-saree-2.png"],
    reviews: [{ rating: 5, comment: "Traditional and elegant." }]
  },
  {
    id: 17,
    brand: "W",
    details: "Women Palazzo Pants",
    description: "Wide-leg palazzos with elastic waistband.",
    price: 699,
    orgprice: 1399,
    off: "50",
    color: "white",
    gender: "women",
    image: "/women-palazzo.png",
    otherImages: ["/women-palazzo-1.png", "/women-palazzo-2.png"],
    reviews: [{ rating: 4, comment: "Very comfortable." }]
  },
  {
    id: 18,
    brand: "ONLY",
    details: "Women Jumpsuit",
    description: "Sleeveless jumpsuit with tie waist.",
    price: 1199,
    orgprice: 2399,
    off: "50",
    color: "red",
    gender: "women",
    image: "/women-jumpsuit.png",
    otherImages: ["/women-jumpsuit-1.png", "/women-jumpsuit-2.png"],
    reviews: [{ rating: 5, comment: "Chic and modern." }]
  },
  {
    id: 19,
    brand: "Global Desi",
    details: "Women Tunic",
    description: "Printed tunic with side slits.",
    price: 899,
    orgprice: 1799,
    off: "50",
    color: "yellow",
    gender: "women",
    image: "/women-tunic.png",
    otherImages: ["/women-tunic-1.png", "/women-tunic-2.png"],
    reviews: [{ rating: 4, comment: "Bright and breezy." }]
  },
  {
    id: 20,
    brand: "Marks & Spencer",
    details: "Women Formal Trousers",
    description: "Slim-fit trousers with stretch fabric.",
    price: 999,
    orgprice: 1999,
    off: "50",
    color: "grey",
    gender: "women",
    image: "/women-trousers.png",
    otherImages: ["/women-trousers-1.png", "/women-trousers-2.png"],
    reviews: [{ rating: 5, comment: "Perfect for office." }]
  }
];

export default womenClothing;